### ISSUE TITLE
host.hostname value in Elasticsearch is 'homeassistant', which is not the actual hostname

### ISSUE THREAD

**Issue by mloebl** [legrego/homeassistant-elasticsearch#101]
**Environment**
Home-Assistant version 0.110.2
Elasticsearch version: 7.7

Relevant `configuration.yml` settings:
```
elastic:
    url: REDACTED
    username: !secret elastic_user
    password: !secret elastic_password
    verify_ssl: true
    ssl_ca_path: !secret elastic_capath
    exclude:
        entities: ['sensor.ted1000_volts', 'sensor.ted1000_kw']
```

**Describe the bug**
My home assistant instance has a different name and a full fqdn, so  home02.somedomain.com .  host.hostname seems to be fixed on "homeassistant" . Not sure if this is expected or not.

**Screenshot**
![image](https://user-images.githubusercontent.com/309719/82850059-cb51b980-9ec8-11ea-86c9-a4e3fd0f2328.png)

**Expected behavior**
Show actual host name for host.hostname

**Additional context**
```
    "host.architecture": "x86_64",
    "host.os.name": "Linux",
    "host.hostname": "homeassistant",
    "tags": [
      "hass"
    ]
```

Thank you!
