### ISSUE TITLE
Missing Static Doc Properties, "This is a bug"

### ISSUE THREAD

**Issue by trebolcinco** [legrego/homeassistant-elasticsearch#151]
Not sure when this started but it is recent.  Am on v0.4.0 of the integration and version 2021.12.2 of HA.  I've searched around through issues and HA sources and not finding any solutions.  

This error originated from a custom integration.

Logger: custom_components.elasticsearch
Source: custom_components/elasticsearch/es_doc_publisher.py:274 
Integration: Elasticsearch (documentation, issues) 
First occurred: January 4, 2022, 12:46:36 PM (25914 occurrences) 
Last logged: 10:27:14 AM

Event for entity [sensor.my_opengarage_dist] is missing static doc properties. This is a bug.
Event for entity [sensor.memory_free] is missing static doc properties. This is a bug.
Event for entity [sensor.processor_use] is missing static doc properties. This is a bug.
Event for entity [switch.other] is missing static doc properties. This is a bug.
Event for entity [weather.dark_sky] is missing static doc properties. This is a bug.

**Comment by legrego** [comment]
Thanks for the report, @trebolcinco. This is certainly a bug with this component -- When I first observed this happening, I thought it was a race condition during component initialization, but that doesn't appear to be the case for your setup since it happened `25914` times:

https://github.com/legrego/homeassistant-elasticsearch/blob/ba7a4a78bd9209993628b99511a3c97108614f63/custom_components/elasticsearch/es_doc_publisher.py#L273-L277

Can you post your component configuration? Either screenshots of your UI-based config, or paste the `configuration.yaml` config if using the file-based configuration. For either, please redact any sensitive information such as hostnames, usernames, and passwords.

**Comment by trebolcinco** [comment]
Am using HACS for elastic setup and am file based yaml, here you go:

```
homeassistant:
  packages: !include_dir_named packages
  customize: !include configuration/customize.yaml
  auth_providers:
    - type: homeassistant

logbook:
  exclude:
    entities:
      - sensor.tiempo_mexico

lovelace:
  mode: yaml
  resources:
    - url: /local/slider-entity-row.js
      type: module
    - url: /local/card-tools.js
      type: module
    - url: /local/community/lovelace-auto-entities/auto-entities.js
      type: module
    - url: /hacsfiles/search-card/search-card.js
      type: module
    - url: /local/card-mod.js
      type: module
    - url: /hacsfiles/battery-state-card/battery-state-card.js
      type: module
    - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
      type: module
    - url: /local/custom_cards/icloud3-event-log-card.js
      type: module
  dashboards:
    ui-other:
      filename: ui-other.yaml
      mode: yaml
      title: Other
      icon: mdi:view-compact
      show_in_sidebar: true
      require_admin: true

default_config:

alarm_control_panel:
  - platform: manual
    name: Office Alarm
    disarm_after_trigger: false
    code: !secret alarm_control_panel_code
    code_arm_required: true
    arming_time: 120
    delay_time: 60
    trigger_time: 600
    disarmed:
      trigger_time: 0
    armed_home:
      arming_time: 0
      delay_time: 0

entity_controller:
  kitchen_lights:                               # serves as a name
    sensor:
      - binary_sensor.top_of_stair_motion_225
      - binary_sensor.kitchen_north_ceiling_227
    entity: light.kitchen                  # required, [entity,entities]
    start_time: sunset - 00:30:00               # required
    end_time: sunrise + 00:30:00                # required
    delay: 500

sonoff:
  username: !secret sonoff_user
  password: !secret sonoff_pass

homekit:
  - filter:
      include_entities:
        - cover.garage_door_2
        - cover.sala_curtains
        - light.kitchen
        - switch.stairs
        - light.sala
        - light.comedor
        - input_boolean.aldama_garden
        - input_boolean.party
        - light.tv_room_fan_143
        - light.gym_fan_24
  - name: Lock Bridge Lower Entry
    mode: accessory
    port: 21065
    filter:
      include_entities:
        - lock.lower_interior_155
  - name: Lock Bridge Aldama
    mode: accessory
    port: 21067
    filter:
      include_entities:
        - lock.aldama_door
  - name: Lock Bridge Casita
    mode: accessory
    port: 21068
    filter:
      include_entities:
        - lock.casita_door
  - name: Lock Bridge Glorieta
    mode: accessory
    port: 21069
    filter:
      include_entities:
        - lock.glorieta_door

python_script:

var:
  battery_threshold:
    friendly_name: 'Battery Threshold'
    initial_value: 15
    icon: mdi:battery

cloud:
  alexa:
    filter:
      include_entities:
        - light.sala
        - light.kitchen
        - light.bathroom
        - light.bedroom
        - light.terraza
        - light.comedor
        - light.office
        - light.all_bathroom
        - light.closet
        - switch.stairs
        - input_boolean.aldama_garden
        - input_boolean.kitchen_evening
        - lock.aldama_door
        - input_boolean.tv_dinner
        - input_boolean.tv
        - switch.ac
        - switch.bedroom_lamps
        - light.office_fan_233
        - light.gym_fan_24
        - light.tv_room_fan_143
        - light.terraza_east_fan_73
        - light.terraza_west_fan_68
    entity_config:
      input_boolean.kitchen_evening:
        name: Kitchen Evening
        description: Kitchen at 50%
      light.office_fan_233:
        name: Office Fan
      light.gym_fan_24:
        name: Gym Fan
      light.tv_room_fan_143:
        name: TV Fan
      light.terraza_east_fan_73:
        name: Terrazza Fan East
      light.terraza_west_fan_68:
        name: Terrazza Fan West
      input_boolean.tv_dinner:
        name: TV Dinner
      input_boolean.tv:
        name: TV Lights

ffmpeg:
  ffmpeg_bin: /usr/bin/ffmpeg

climate:
  - platform: sensibo
    api_key: 00000

rest_command:
  reboot_opengarage:
    url: !secret opengarage_url
    method: GET

influxdb:
  host: !secret influx_host

recorder:
  db_url: !secret db_url
  purge_keep_days: 5

frontend:
  themes: !include_dir_merge_named themes

group: !include configuration/groups.yaml
scene: !include configuration/scenes.yaml
light:  !include configuration/lights.yaml
automation: !include_dir_merge_list configuration/automations
switch: !include configuration/switches.yaml
input_boolean: !include configuration/input_booleans.yaml
input_number: !include configuration/input_numbers.yaml
input_text: !include configuration/input_text.yaml
input_datetime:
input_select:
image:
script: !include configuration/scripts.yaml
sensor: !include configuration/sensors.yaml
binary_sensor: !include configuration/binary_sensors.yaml
cover: !include configuration/covers.yaml
lock: !include configuration/locks.yaml
camera: !include configuration/camera.yaml
device_tracker: !include configuration/device_tracker.yaml
notify: !include configuration/notify_group.yaml
alert: !include configuration/alert.yaml

logger:
  default: warning
  logs:
    homeassistant.components.upnp: error
    homeassistant.config_entries: error
    homeassistant.custom_components: debug
```
