### ISSUE TITLE
Settings for index_format and alias are not applied

### ISSUE THREAD

**Issue by sejnub** [legrego/homeassistant-elasticsearch#48]
**Environment**
Home-Assistant version: hass.io 0.86.2
Elasticsearch version: 6.5.4

Relevant `configuration.yml` settings:

```yml
elastic:
  # URL should point to your Elasticsearch cluster
  url: http://elasticsearch.internal:9200
  index_format:     "hass"
  alias:            "hass-active" 
  publish_frequency: 10
  rollover_max_size: 1gb
  #rollover_max_age: 
  #rollover_max_docs: 
```

**Describe the bug**
When I restart my hass.io the settings for index_format and alias are not used. Instead in elasticseach I only have one index named "active-hass-index-v2" into which data is added.

**Expected behavior**
I expect the index "hass-00001" and the alias "hass-active" to be created.

**To Reproduce**
Load the qouted settings into hass.io and restart hass.io

**Additional context**
There is only one index template in elasticsearch which looks like this:

```json
{
  "order": 0,
  "index_patterns": [
    "hass-events-v2*"
  ],
  "settings": {
    "index": {
      "number_of_shards": "1"
    }
  },
  "mappings": {
    "doc": {
      "dynamic": "strict",
      "properties": {
        "domain": {
          "type": "keyword"
        },
        "object_id": {
          "type": "keyword"
        },
        "entity_id": {
          "type": "keyword"
        },
        "attributes": {
          "type": "object",
          "dynamic": true,
          "properties": {
            "es_location": {
              "type": "geo_point"
            }
          }
        },
        "@timestamp": {
          "type": "date"
        },
        "value": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword",
              "ignore_above": 2048
            },
            "float": {
              "type": "float",
              "ignore_malformed": true
            }
          }
        }
      }
    }
  },
  "aliases": {
    "all-hass-events": {}
  }
}
```

**Question**

What do I have to do to make homeassistant-elasticsearch apply the new settings?
