### ISSUE TITLE
Switch to ILM instead of rollover

### ISSUE THREAD

**Issue by dsztykman** [legrego/homeassistant-elasticsearch#58]
**Uses ILM instead of rollover for ES 6.7 and higher**
See documentation [here](https://www.elastic.co/guide/en/elasticsearch/reference/6.7/_setting_up_a_new_policy.html
)

**Comment by legrego** [comment]
Thanks for the issue @dsztykman! This is something I've wanted to do for a while, so now that ILM is publicly available, we can get started on this 🎉

**Comment by legrego** [comment]
I'd honestly _love_ to remove the rollover code that we currently have, as it's rather clunky. OTOH, forcing users to upgrade to 6.7 isn't necessarily ideal either.

Any thoughts?

👍 : Rip out rollover
👎 : Keep it in!

**Comment by dsztykman** [comment]
Very selfish from me but let's just rip out rollover 👍

**Comment by legrego** [comment]
To keep things simple, I was thinking of starting off with a simple hot / delete setup.

Maybe something like:

```yaml
# configuration.yml
elastic:
  url: '....'
  ilm:
    enabled: True # (will detect if available via license)
    hot_max_size: 30GB
    hot_max_age: #(Default None)
    delete_min_age: 356d #(Default None)
```

Would build a policy similar to the following:
```
PUT _ilm/policy/hass_policy   
{
  "policy": {                       
    "phases": {
      "hot": {                      
        "actions": {
          "rollover": {             
            "max_size": "30GB"
          }
        }
      },
      "delete": {
        "min_age": "365d",           
        "actions": {
          "delete": {}              
        }
      }
    }
  }
}
```

Thoughts on this?
