### ISSUE TITLE
Insufficient privileges provided with the README example

### ISSUE THREAD

**Issue by untergeek** [legrego/homeassistant-elasticsearch#66]
**Environment**
Home-Assistant version: 0.93.2
Elasticsearch version: 7.1.0

Relevant `configuration.yml` settings:
```yml
elastic:
  url: https://d4eec97ef7554e85987327576a2af170.ece.REDACTED.ORG:9243
  ssl_ca_path: /path/to/letsencryptCA.pem
  username: !secret elastic_user
  password: !secret elastic_pass
  publish_frequency: 60
  request_rollover_frequency: 600
  rollover_max_size: 3gb
```

**Describe the bug**
The role suggestion you offer does not cover all needed roles.

```
Error creating initial index/alias: AuthorizationException(403, 'security_exception', 'action [indices:admin/aliases] is unauthorized for user [hass_writer]')
…
Error performing rollover: AuthorizationException(403, 'security_exception', 'action [indices:admin/rollover] is unauthorized for user [hass_writer]')
```

And because of these, it can't write to the index:

```
Error publishing documents to Elasticsearch: ('500 document(s) failed to index.'
```

**To Reproduce**
1. Create a `hass_writer` user with the role as defined in the README

**Expected behavior**
The README instructions should include all necessary roles and permissions needed for a user to successfully write to Elasticsearch the first try.
