### ISSUE TITLE
Add queries as sensors

### ISSUE THREAD

**Issue by wickedsun** [legrego/homeassistant-elasticsearch#76]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to make queries and return the result to HomeAssistant, this would be useful for geofencing, for example, as I send all my data to Elastic, but not all data flows through HomeAssistant.

**Describe the solution you'd like**
A plugin to create queries into ElasticSearch as sensors in HomeAssistant.

**Additional context**

**Comment by legrego** [comment]
Hey @wickedsun, thanks for opening this issue.

This is an interesting idea. How do you envision this working with a query that returns multiple hits, or multiple buckets in an aggregation?

For queries that return a single hit, I could see something like this working:

```yml
elastic:
   query_sensors:
     - name: sensor_1
     query: '{"query": { "terms": {...} }}'
     field: 'my.document.field'
```

Where `my.document.field` represents a field in the document returned by the query
