### ISSUE TITLE
Allow forcing lower-casing of entity ids.

### ISSUE THREAD

**Issue by untergeek** [legrego/homeassistant-elasticsearch#79]
Some devices append a `.Battery_State` while some append `.battery_state`.

This could be reconciled by forcing lower-case, and/or a separate mapping output that is forced into a lower-case state.

**Comment by legrego** [comment]
What do you think about supporting a config similar to the following:

```yaml
# configuration.yaml
elastic:
   url: http://localhost:9200
   customize_entities:
     - 'switch.living_room_light':
       force_lower_case: true
```

This could allow for a flexible config system so that we could also support  https://github.com/legrego/homeassistant-elasticsearch/issues/78:

```yaml
# configuration.yaml
elastic:
   url: http://localhost:9200
   customize_entities:
     - 'switch.living_room_light':
       force_lower_case: true
       excluded_attributes: ["battery_level"]
```
