### ISSUE TITLE
ilm_max_size vs ilm_hot_max_size

### ISSUE THREAD

**Issue by kkellner** [legrego/homeassistant-elasticsearch#88]
**Environment**
Home-Assistant version: 0.106
Elasticsearch version: 0.2.0

Relevant `configuration.yml` settings:
```yml
elastic:
    url: SOME_URL
    publish_frequency: 2
    only_publish_changed: true
    ilm_hot_max_size: 10gb
    ilm_delete_after: 30d
```

**Describe the bug**
The readme documentation lists `ilm_hot_max_size` which does not work.  Looks like the real property name is `ilm_max_size`.

**To Reproduce**
Use the above yaml - validation will fail.
