### ISSUE TITLE
Upgrade to 0.2.0 no events in Elastic

### ISSUE THREAD

**Issue by kkellner** [legrego/homeassistant-elasticsearch#89]
After upgrading from 0.1.3 to 0.2.0 I needed to update the configuration as follows:

My version 0.1.3 config:

```yaml
elastic:
    url: SOME_URL
    publish_frequency: 2
    only_publish_changed: true
    rollover_max_age: 1d
    exclude:
      entities: [ 'sensor.es_publish_queue' ]
      domains: [ 'sun' ]
```
My version 0.2.0 config:
```yaml
elastic:
    # URL should point to your Elasticsearch cluster
    url: SOME_URL
    publish_frequency: 2
    only_publish_changed: true
    ilm_max_size: 10gb
    ilm_delete_after: 30d
    exclude:
      entities: [ 'sensor.es_publish_queue' ]
      domains: [ 'sun' ]
```

Home Assistant restarted without issues with the above change, however I am not getting any events (visible) in Kibana (Elasticsearch).   Is there an upgrade step I missed?   Here are my current indexes:

![image](https://user-images.githubusercontent.com/9540241/76819857-0ea7f180-67cf-11ea-9b9a-17793e435d7c.png)

Events stopped after 21:18:

![image](https://user-images.githubusercontent.com/9540241/76820200-16b46100-67d0-11ea-8745-7fd58ede0b92.png)

Does something need to be updated on the Elasticsearch side?
