### ISSUE TITLE
Elasticsearch tries to expand dots in JSON keys

### ISSUE THREAD

**Issue by untergeek** [legrego/homeassistant-elasticsearch#92]
**Environment**
Home-Assistant version: 0.107.4
Elasticsearch version: 7.6.2

Relevant `configuration.yml` settings:
```yml
elastic:
  cloud_id: REDACTED
  ssl_ca_path: REDACTED
  username: !secret elastic_user
  password: !secret elastic_pass
  publish_frequency: 60
  ilm_enabled: true
  ilm_policy_name: home-assistant
  ilm_max_size: 6gb
  ilm_delete_after: 14d
  exclude:
    domains: ['automation', 'group', 'input_select', 'input_text', 'remote', 'script', 'timer', 'zone']
```

**Describe the bug**
When a sub-key of `hass.attributes` (and potentially others) contains dots, Elasticsearch will try to expand that key into a nested structure.

**To Reproduce**
For example, when trying to index this sample (extracted from `home-assistant.log`):
```
  "hass.attributes": {
    "some.user@gmail.com - Roku Ultra": "Movie Title (1900)",
    "unit_of_measurement": "Watching",
    "friendly_name": "Plex (LibraryName)",
    "icon": "mdi:plex"
  },
```
You will get an error like this:
```
      {
        "type" : "class_cast_exception",
        "reason" : "class_cast_exception: class org.elasticsearch.index.mapper.TextFieldMapper cannot be cast to class org.elasticsearch.index.mapper.ObjectMapper (org.elasticsearch.index.mapper.TextFieldMapper and org.elasticsearch.index.mapper.ObjectMapper are in unnamed module of loader 'app')"
      }
```

Escaping the dots does not correct the behavior, though replacing with `_` or `_dot_` does work.

**Expected behavior**
I do not believe that the original key can be preserved due to Elasticsearch's innate behavior.

Replacing `.` with `_` or `_dot_` will permit the document to be indexed, even if it is slightly modified.

**Additional context**
Initially discovered [here](https://github.com/legrego/homeassistant-elasticsearch/issues/91#issuecomment-607495867).
